#!/bin/bash -e
#########################################
# change mandatory
#########################################

# this declares the identifier of the synapse server - this is NOT you url
# see: https://github.com/matrix-org/synapse/blob/master/INSTALL.md#choosing-your-server-name
SYNAPSE_SERVER_NAME=xxx.de

# this declares the base of the url to access the synapse server. Used in homeserver.yaml and reverse proxy configuration.
# explicitly provide the port, even if its port 443!
SYNAPSE_PUBLIC_BASEURL=https://matrix.xxx.de:8443

# synapse container host port. Used in the reverse proxy configuration.
SYNAPSE_HOST_PORT_HTTP=8008

# make sure the uid and gid exists in your system. User for *_VOLUME_HOST_PATH and as UID/GID in synapse and postgresql
SYNAPSE_UID=1026
SYNAPSE_GID=100

# enable element, valid options: yes, no
ELEMENT_ENABLED=yes
# this declares the base of the url to access the element server. Used in the reverse proxy configuration.
# make sure to access element using it's public url.
# explicitly provide the port, even if its port 443!
ELEMENT_PUBLIC_BASEURL=https://element.xxx.de:8443

# element container host port. Used in the reverse proxy configuration.
ELEMENT_HOST_PORT_HTTP=8888

MAUTRIX_WHATSAPP_ENABLED=no
MAUTRIX_WHATSAPP_HOST_PORT_HTTP=29318
MAUTRIX_WHATSAPP_BOT_USERNAME="whatsappbot"
MAUTRIX_WHATSAPP_BOT_DISPLAYNAME="WhatsApp bridge bot"
MAUTRIX_WHATSAPP_BOT_AVATAR="mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr"
MAUTRIX_WHATSAPP_WHATSAPP_OS_NAME="Mautrix-WhatsApp bridge"
MAUTRIX_WHATSAPP_WHATSAPP_BROWSER_NAME="mx-wa"
MAUTRIX_WHATSAPP_BRIDGE_PERMISSION=()
SYNAPSE_VOLUME_HOST_PATH=/volume2/docker/matrix/synapse/data
ELEMENT_VOLUME_HOST_PATH=/volume2/docker/matrix/element/config
POSTGRES_VOLUME_HOST_PATH=/volume2/docker/matrix/db/data
MAUTRIX_WHATSAPP_VOLUME_HOST_PATH=/volume2/docker/matrix/mautrix-whatsapp/data

#########################################
# change optional
#########################################

SYNAPSE_MAX_UPLOAD_SIDE=64M
SYNAPSE_ENABLE_REGISTRATION=true
SYNAPSE_REPORT_STATS=no
SYNAPSE_TZ=Europe/Berlin
SYNAPSE_NO_TLS=true

POSTGRES_HOST=db
POSTGRES_DB=synapse
POSTGRES_USER=synapse
POSTGRES_PASSWORD=synapse

#########################################
# change if you know what you're doing
#########################################

SYNAPSE_IMAGE=matrixdotorg/synapse:latest
ELEMENT_IMAGE=vectorim/element-web:latest
MAUTRIX_WHATSAPP_IMAGE=dock.mau.dev/tulir/mautrix-whatsapp:latest
POSTGRES_IMAGE=postgres:13.1-alpine

SYNAPSE_DATA_DIR=/data
SYNAPSE_CONFIG_DIR=/data
SYNAPSE_CONFIG_PATH=${SYNAPSE_CONFIG_DIR}/homeserver.yaml
SYNAPSE_WORKER=synapse.app.homeserver

# this is needed to configure the database as synapse needs it! Don't touch!
POSTGRES_INITDB_ARGS="--encoding=UTF-8 --lc-collate=C --lc-ctype=C"

# project name, will be prefix to *_SERVICE_NAME in container and docker network names
DOCKER_COMPOSE_PROJECT=matrix
